language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - OWNER_NAME=BrightspaceUILabs
  - REPO_NAME=autocomplete
  - SAUCE_USERNAME: Gaudi1
  # SAUCE_ACCESS_KEY
  - secure: fxPP+am1qWXmYZRXJl3I27bWqu/B14qXuwybbUC3bUqr7YjekXdllmMgH+aPYMtF1FDJl2WB9HooyLet7ubeKnJB49d9iMDEemciVsJJriRn5o+Hb5H4m97wU1I0Obw8EHb5nYy6KHIEoZIsmu1S9YQvXDPpUG1jqC8pWZ237n5rRwXs2tulczGg1Uun1hrVYHunjkg+hzlp13y4GEfKhA6UTtVv2OYNTcagQSDox/I6eVyGQIJ1s8Xfdn/uVw2feDYpvVVHfFMnCfhLsSZDZe11N3bl0ZXV31EqZ0Vf8z9+JYMvb3TsnTISwkLYHvrvVb2ywofsI5izWTI+3a2CPqzWhSC3BN476whJ4ZymBNQZiNea02nkBQrFJQL6iOXZ663NtFkqJc+jQcZQ7cCEkB14JKIQASnm71TqRaL/nEL/YMcO41A0V9bvHxRYet2t6YARY5KJuuhrl24wbgYyGayhvv3dy0o+NU77gYGScIOc+5YhZX3Z/tHPFZNrMieyxHilOpmeOaodRNnkdd6kw8RjrWjM1SDv9DcQQNDBUG3DMr4cahXSfRafZlYAjmdmv6Gs3GNQehb5nLtAz0/eyAirueZUQTvRSmpvPRa7pR70wE8RyUWoUQY13VZFVb8KPe1b5awDZpAdbWTrgHMOEZOaa+AaraUgan4EY0wT5Xg=
  # GITHUB_RELEASE_TOKEN
  - secure: xmDh7JpfEtPubuYzQhkeoAHYE+nN3He8ZWzKD8qw9pgSHW0S1NLmqduAmBLuL+Vh0N6OSfI6J69vu/2jgSB2sb4o46dYovvjm74msHbiDdNhStwvSm2i6Pl7Se+eyRB/dr7VAhIqp8mQ7H9wI8faS7zSn+iFT0VzS4ZPNBh4cqLuqequ0v5iW07aCEVmsn5jH/C4PvYBolRpwDSJRsHyC81HfQQG1k73Ls9q5vSUec84MM5zBdEgrO/o+4fPAmDgN4QppwCOIAz8t6Bruwdj/h7EAJJTwuhELwfph/Q3t4jh/KTPPboHDyWZdYsXB76b18isnEo57mYMeGljkHqEJpYwZbjf83GcleEuMIzFc0Ca1kQ+JYYCkerUYckgq6FNUUotkfYQgUvnhhIsGA//LirtTes9zmX7e3/MX7Vl1HD2optKM2ZeoPHOXmhvRreGFctaoP6ffSKONVPTyxS8PlzCsxNm1lkGpglwM/4XA+T0EG8u+ILvniKZp+/mTixOzrBs/qGep3mM6CPRkd3nzJrbuBIAmfS+5l9nq+90SxFhMD/NdzaKfPE62pdl/jap3o5b4H46oL4g8d7gBc1jGZ220Vtys4ufwGCWhpeau/5sa4kJpPzNIGkqRy+FJlWN1H8sPijk+/0OxGNzegjROUzAFK2g3NrgYvd5VUoSDgQ=
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # 40ad......7a38
    secure: wD9o+8u1BTQ+5MSJqtZuyhUJAjZkUh2mGDwMH8T3fF1yXALyzis7ZTlcrf8Z7mDMLkwxrLMWt5rhpvV3K5A7nEibxbWVN88jaqXiHpR1YsOwDNjdtF8eD511Ic6djA7NtWacLBfDOQAC1pWF+ruBZpaWRBBKCDRXVdVbLipBQoweTQuLm77SF3tz5Au5Xm1JlC7p7ePJvb8gCz8eucZzYf2kOlmG1Nyk99dibzCWuPRDVtdFMM8hDDQQuo06a2OzZPxxov3IkorjQ5KCc1BLOwLu2c7G8jZrRwObyM2DYA8I4oP09cVR1JCXIIRm6l1nE/K+PPLjauD1UglN7yJy0VaQRo/22LhJNPJpoWr31yHMr9FxYyyytGY6bC9oYMjBfrYUQaot/21z65LIZgYPS/4cg0fYW1uvIUNRG35VyTkSYxLmt2V4fP1P6YGIFoHhU41ZbhG4ZkRP6pIP3mJ+lnm1dq8eeB9J8N/KWiQWcabqsw8vXiv6WAFbCAS9XJfCUGH8xs9hBbJfdTsc2Zp5k5tX02qDYf/Qd+jgrBwTiS45wXgMeCu9Nondpp2UCPKBe3VRdqFOdT2hFf2bt7cBO+EAb5KJhq6iDtmh6xDD5dyQGEl2IJtU/Kb8+wb2J/YmblheCkd5okIbNYK2OVwoV774EYWK7pGwstTQGpvEvmI=
  on:
    tags: true
    repo: BrightspaceUILabs/autocomplete
