name: CI
on: pull_request
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: |
          npm install
          npm install @web/test-runner-saucelabs --no-save
      - name: Lint (JavaScript)
        run: npm run lint:eslint
      - name: Lint (CSS)
        run: npm run lint:style
      - name: Unit Tests (SauceLabs)
        run: npx web-test-runner --config web-test-runner.sauce.config.js
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_DESIRE2LEARN }}
          SAUCE_USERNAME: Desire2Learn
